import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  return knex.schema.alterTable('releases', (table) => {
    table.dropColumn('text')
    table
      .integer('fk_book')
      .references('id')
      .inTable('books')
      .onDelete('CASCADE')
    table.text('release_status').defaultTo('active')
    table.text('release_type').defaultTo('')
    table.text('submission_date').defaultTo('')
    table.text('acceptance_date').defaultTo('')
    table.text('pre_order_date').defaultTo('')
    table.text('publication_date').defaultTo('')
    table.boolean('preorder').defaultTo(false)
    table.text('sku').defaultTo('')
    table.text('trim_size').defaultTo('')
    table.text('binding').defaultTo('')
    table.integer('page_count').defaultTo(0)
    table.float('spine_width').defaultTo(0)
    table.text('color').defaultTo('')
    table.text('paper').defaultTo('')
    table.text('cover_finish').defaultTo('')
    table.integer('carton_quantity').defaultTo(0)
    table.float('weight').defaultTo(0)
    table.boolean('full_distribution').defaultTo(true)
    table.text('returnable').defaultTo('no')
    table.boolean('enable_look_inside').defaultTo(true)
    table.boolean('kdp_select').defaultTo(false)
    table.boolean('kdp_match_book').defaultTo(false)
    table.text('asin').defaultTo('')
    table.boolean('drm').defaultTo(false)
    table.text('notes').defaultTo('')
    table.text('created_at')
    table
      .integer('fk_created_by')
      .references('id')
      .inTable('users')
      .onDelete('RESTRICT')
  })
}

export async function down(knex: Knex): Promise<void> {
  return knex.schema.alterTable('releases', (table) => {
    table.dropColumn('fk_book')
    table.dropColumn('release_status')
    table.dropColumn('release_type')
    table.dropColumn('submission_date')
    table.dropColumn('acceptance_date')
    table.dropColumn('pre_order_date')
    table.dropColumn('publication_date')
    table.dropColumn('preorder')
    table.dropColumn('sku')
    table.dropColumn('trim_size')
    table.dropColumn('binding')
    table.dropColumn('page_count')
    table.dropColumn('spine_width')
    table.dropColumn('color')
    table.dropColumn('paper')
    table.dropColumn('cover_finish')
    table.dropColumn('carton_quantity')
    table.dropColumn('weight')
    table.dropColumn('full_distribution')
    table.dropColumn('returnable')
    table.dropColumn('enable_look_inside')
    table.dropColumn('kdp_select')
    table.dropColumn('kdp_match_book')
    table.dropColumn('asin')
    table.dropColumn('drm')
    table.dropColumn('notes')
    table.dropColumn('created_at')
    table.dropColumn('fk_created_by')
  })
}
