import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  await knex.schema.alterTable('books', (table) => {
    table.dropColumn('text')
    table
      .integer('fk_imprint')
      .references('id')
      .inTable('imprints')
      .onDelete('RESTRICT')
    table.string('derived_type', 32).defaultTo('original')
    table
      .integer('fk_derived_from')
      .references('id')
      .inTable('books')
      .onDelete('RESTRICT')
    table.string('title').defaultTo('')
    table.string('subtitle').defaultTo('')
    table.string('accounting_code', 255).defaultTo('')
    table.string('isbn_paperback', 30).defaultTo('')
    table.string('isbn_hardcover', 30).defaultTo('')
    table.string('isbn_epub', 30).defaultTo('')
    table.string('isbn_ibooks', 30).defaultTo('')
    table.string('book_status').defaultTo('contract negotiation')
    table.string('copyright_holder').defaultTo('')
    table.string('copyright_year').defaultTo('')
    table.string('language').defaultTo('')
    table.string('short_description', 1000).defaultTo('')
    table.string('long_description', 5000).defaultTo('')
    table.string('back_cover_text', 6000).defaultTo('')
    table.string('jacket_front_text').defaultTo('')
    table.string('jacket_back_text').defaultTo('')
    table.boolean('is_public_domain').defaultTo(false)
    table.string('keywords', 2000).defaultTo('')
    table.string('bisac_code_1').defaultTo('')
    table.string('bisac_code_2').defaultTo('')
    table.string('bisac_code_3').defaultTo('')
    table.string('bisac_name_1').defaultTo('')
    table.string('bisac_name_2').defaultTo('')
    table.string('bisac_name_3').defaultTo('')
    table.string('amazon_category_1').defaultTo('')
    table.string('amazon_category_2').defaultTo('')
    table.string('amazon_category_3').defaultTo('')
    table.string('thema').defaultTo('')
    table.string('audience').defaultTo('')
    table.string('series_name').defaultTo('')
    table.integer('series_number').defaultTo(0)
    table.string('edition_name').defaultTo('')
    table.integer('edition_number').defaultTo(0)
    table.boolean('right_to_left').defaultTo(false)
    table.string('author').defaultTo('')
    table.string('contains_prior_work').defaultTo('')
    table.string('contains_others_work').defaultTo('')
    table.string('web_domain').defaultTo('')
    table.integer('published_word_count').defaultTo(0)
    table.integer('image_count').defaultTo(0)
    table.string('press_contact').defaultTo('')
    table.string('legal_notice').defaultTo('')
    table.string('featured_ads').defaultTo('')
    table.string('notes').defaultTo('')
    table.string('created_at', 32)
    table
      .integer('fk_created_by')
      .references('id')
      .inTable('users')
      .onDelete('RESTRICT')
  })
}

export async function down(knex: Knex): Promise<void> {}
