import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  return knex.schema.alterTable('pricing', (table) => {
    table.dropColumn('text')
    table
      .integer('fk_release')
      .references('id')
      .inTable('releases')
      .onDelete('CASCADE')
    table.string('start_date', 32).defaultTo('')
    table.string('expiration_date', 32).defaultTo('')
    table.float('us_srp').defaultTo(0)
    table.float('us_discount').defaultTo(0)
    table.string('us_returnable').defaultTo('no')
    table.float('uk_srp').defaultTo(0)
    table.float('uk_discount').defaultTo(0)
    table.string('uk_returnable').defaultTo('no')
    table.float('eu_srp').defaultTo(0)
    table.float('eu_discount').defaultTo(0)
    table.string('eu_returnable').defaultTo('no')
    table.float('ca_srp').defaultTo(0)
    table.float('ca_discount').defaultTo(0)
    table.string('ca_returnable').defaultTo('no')
    table.float('au_srp').defaultTo(0)
    table.float('au_discount').defaultTo(0)
    table.string('au_returnable').defaultTo('no')
    table.float('gc_srp').defaultTo(0)
    table.float('gc_discount').defaultTo(0)
    table.string('gc_returnable').defaultTo('no')
    table.string('created_at', 32)
    table
      .integer('fk_created_by')
      .references('id')
      .inTable('users')
      .onDelete('RESTRICT')
  })
}

export async function down(knex: Knex): Promise<void> {
  return knex.schema.alterTable('pricing', (table) => {
    table.dropColumn('fk_release')
    table.dropColumn('start_date')
    table.dropColumn('expiration_date')
    table.dropColumn('us_srp')
    table.dropColumn('us_discount')
    table.dropColumn('us_returnable')
    table.dropColumn('uk_srp')
    table.dropColumn('uk_discount')
    table.dropColumn('uk_returnable')
    table.dropColumn('eu_srp')
    table.dropColumn('eu_discount')
    table.dropColumn('eu_returnable')
    table.dropColumn('ca_srp')
    table.dropColumn('ca_discount')
    table.dropColumn('ca_returnable')
    table.dropColumn('au_srp')
    table.dropColumn('au_discount')
    table.dropColumn('au_returnable')
    table.dropColumn('gc_srp')
    table.dropColumn('gc_discount')
    table.dropColumn('gc_returnable')
    table.dropColumn('created_at')
    table.dropColumn('fk_created_by')
  })
}
