import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  return knex.schema.alterTable('contributors', (table) => {
    table.dropColumn('text')
    table
      .integer('fk_book')
      .references('id')
      .inTable('books')
      .onDelete('CASCADE')
    table.text('contributor_role').defaultTo('')
    table.text('legal_name').defaultTo('')
    table.text('published_name').defaultTo('')
    table.text('biography').defaultTo('')
    table.text('email').defaultTo('')
    table.text('address').defaultTo('')
    table.text('phone').defaultTo('')
    table.text('wikipedia_page').defaultTo('')
    table.text('amazon_author_page').defaultTo('')
    table.text('author_website').defaultTo('')
    table.text('twitter').defaultTo('')
    table.text('instagram').defaultTo('')
    table.text('facebook').defaultTo('')
    table.text('linkedin').defaultTo('')
    table.text('goodreads').defaultTo('')
    table.text('tiktok').defaultTo('')
    table.text('notes').defaultTo('')
    table.text('created_at')
    table
      .integer('fk_created_by')
      .references('id')
      .inTable('users')
      .onDelete('RESTRICT')
  })
}

export async function down(knex: Knex): Promise<void> {
  return knex.schema.alterTable('contributors', (table) => {
    table.dropColumn('fk_book')
    table.dropColumn('contributor_role')
    table.dropColumn('legal_name')
    table.dropColumn('published_name')
    table.dropColumn('biography')
    table.dropColumn('email')
    table.dropColumn('address')
    table.dropColumn('phone')
    table.dropColumn('wikipedia_page')
    table.dropColumn('amazon_author_page')
    table.dropColumn('author_website')
    table.dropColumn('twitter')
    table.dropColumn('instagram')
    table.dropColumn('facebook')
    table.dropColumn('linkedin')
    table.dropColumn('goodreads')
    table.dropColumn('tiktok')
    table.dropColumn('notes')
    table.dropColumn('created_at')
    table.dropColumn('fk_created_by')
  })
}
