import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  return knex.schema.alterTable('releases', (table) => {
    table.dropColumn('text')
    table
      .integer('fk_book')
      .references('id')
      .inTable('books')
      .onDelete('CASCADE')
    table.string('release_status').defaultTo('active')
    table.string('release_type').defaultTo('')
    table.string('submission_date', 32).defaultTo('')
    table.string('acceptance_date', 32).defaultTo('')
    table.string('pre_order_date', 32).defaultTo('')
    table.string('publication_date', 32).defaultTo('')
    table.boolean('preorder').defaultTo(false)
    table.string('sku').defaultTo('')
    table.string('trim_size').defaultTo('')
    table.string('binding').defaultTo('')
    table.integer('page_count').defaultTo(0)
    table.float('spine_width').defaultTo(0)
    table.string('color').defaultTo('')
    table.string('paper').defaultTo('')
    table.string('cover_finish').defaultTo('')
    table.integer('carton_quantity').defaultTo(0)
    table.float('weight').defaultTo(0)
    table.boolean('full_distribution').defaultTo(true)
    table.string('returnable').defaultTo('no')
    table.boolean('enable_look_inside').defaultTo(true)
    table.boolean('kdp_select').defaultTo(false)
    table.boolean('kdp_match_book').defaultTo(false)
    table.string('asin').defaultTo('')
    table.boolean('drm').defaultTo(false)
    table.string('notes').defaultTo('')
    table.string('created_at', 32)
    table
      .integer('fk_created_by')
      .references('id')
      .inTable('users')
      .onDelete('RESTRICT')
  })
}

export async function down(knex: Knex): Promise<void> {
  return knex.schema.alterTable('releases', (table) => {
    table.dropColumn('fk_book')
    table.dropColumn('release_status')
    table.dropColumn('release_type')
    table.dropColumn('submission_date')
    table.dropColumn('acceptance_date')
    table.dropColumn('pre_order_date')
    table.dropColumn('publication_date')
    table.dropColumn('preorder')
    table.dropColumn('sku')
    table.dropColumn('trim_size')
    table.dropColumn('binding')
    table.dropColumn('page_count')
    table.dropColumn('spine_width')
    table.dropColumn('color')
    table.dropColumn('paper')
    table.dropColumn('cover_finish')
    table.dropColumn('carton_quantity')
    table.dropColumn('weight')
    table.dropColumn('full_distribution')
    table.dropColumn('returnable')
    table.dropColumn('enable_look_inside')
    table.dropColumn('kdp_select')
    table.dropColumn('kdp_match_book')
    table.dropColumn('asin')
    table.dropColumn('drm')
    table.dropColumn('notes')
    table.dropColumn('created_at')
    table.dropColumn('fk_created_by')
  })
}
