import type { Knex } from 'knex'

export async function up(knex: Knex): Promise<void> {
  return knex.schema.alterTable('marketings', (table) => {
    table.dropColumn('text')
    table
      .integer('fk_book')
      .references('id')
      .inTable('books')
      .onDelete('CASCADE')
    table.text('goodreads_reviews_link').defaultTo('')
    table.text('amazon_reviews_link').defaultTo('')
    table.text('amazon_a_plus_link').defaultTo('')
    table.text('a_plus_description_1').defaultTo('')
    table.text('a_plus_text_1').defaultTo('')
    table.boolean('a_plus_is_live_1').defaultTo(false)
    table.text('a_plus_rejection_reason_1').defaultTo('')
    table.text('a_plus_image_1').defaultTo('')
    table.text('a_plus_description_2').defaultTo('')
    table.text('a_plus_text_2').defaultTo('')
    table.boolean('a_plus_is_live_2').defaultTo(false)
    table.text('a_plus_rejection_reason_2').defaultTo('')
    table.text('a_plus_image_2').defaultTo('')
    table.text('a_plus_description_3').defaultTo('')
    table.text('a_plus_text_3').defaultTo('')
    table.boolean('a_plus_is_live_3').defaultTo(false)
    table.text('a_plus_rejection_reason_3').defaultTo('')
    table.text('a_plus_image_3').defaultTo('')
    table.text('notes').defaultTo('')
    table.text('created_at')
    table
      .integer('fk_created_by')
      .references('id')
      .inTable('users')
      .onDelete('RESTRICT')
  })
}

export async function down(knex: Knex): Promise<void> {
  return knex.schema.alterTable('marketings', (table) => {
    table.text('text').defaultTo('')
    table.dropColumn('fk_book')
    table.dropColumn('goodreads_reviews_link')
    table.dropColumn('amazon_reviews_link')
    table.dropColumn('amazon_a_plus_link')
    table.dropColumn('a_plus_description_1')
    table.dropColumn('a_plus_text_1')
    table.dropColumn('a_plus_is_live_1')
    table.dropColumn('a_plus_rejection_reason_1')
    table.dropColumn('a_plus_image_1')
    table.dropColumn('a_plus_description_2')
    table.dropColumn('a_plus_text_2')
    table.dropColumn('a_plus_is_live_2')
    table.dropColumn('a_plus_rejection_reason_2')
    table.dropColumn('a_plus_image_2')
    table.dropColumn('a_plus_description_3')
    table.dropColumn('a_plus_text_3')
    table.dropColumn('a_plus_is_live_3')
    table.dropColumn('a_plus_rejection_reason_3')
    table.dropColumn('a_plus_image_3')
    table.dropColumn('notes')
    table.dropColumn('created_at')
    table.dropColumn('fk_created_by')
  })
}
